### ISSUE TITLE
Is this an extension for graphql-go or standalone project?

### ISSUE THREAD

**Issue by sasso** [graph-gophers/graphql-transport-ws#7]
Is there a reason this code is not a part of graphql-go project? if this is meant as an extension then I would suggest that we call this project **graphql-go-subscriptions** or something that shows that this project is an extension of **graphql-go**

**Comment by pavelnikolov** [comment]
Yes, this is an extension for `graphql-go`. The idea is that this is a reference WS implementation and you might want to implement different one or even use entirely different transport. Ideally, the grahpql library should be transport agnostic.
I do not agree to `graphql-go-subscriptions` because this is just one transport for subscriptions. You can use any pub/sub system for that. Maybe `graphql-go-tranport-ws`?
